trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Container Images
  jobs:
  - job: Build_Windows_Container
    timeoutInMinutes: 400
    displayName: Build Windows Container
    pool:
      name: Default
      demands:
      - Agent.OS -equals Windows_NT
      - Agent.OSArchitecture -equals X64
    steps:
    - task: Docker@2
      displayName: Build the windows image
      inputs:
        command: build
        repository: 'qt-build-env-windows'
        dockerfile: '$(Build.SourcesDirectory)/DockerFile-windows'
        containerRegistry: 'dfsbuildcontainer.azurecr.io'
        tags: |
          $(tag)
  - job: Build_Linux_Container
    timeoutInMinutes: 400
    displayName: Build Linux Container
    pool:
      name: Default
      demands:
      - Agent.OS -equals Linux
      - Agent.OSArchitecture -equals X64
    steps:
    - task: Docker@2
      displayName: Build/Push the linux image
      inputs:
        command: buildAndPush
        repository: 'qt-build-env-linux'
        dockerfile: '$(Build.SourcesDirectory)/DockerFile-linux'
        containerRegistry: 'dfsbuildcontainer.azurecr.io'
        tags: |
          $(tag)