# Compile Environment for Qt Applications (linux)
# DF Supply, Inc.
# Scott Moore
# 2/24/2022

FROM registry.access.redhat.com/ubi9/ubi

RUN \
	yum update -y && \
	yum install yum-utils -y && \
	yum-config-manager --enable codeready-builder-for-rhel-9-x86_64-rpms && \
	yum install python3 wget make cmake *mesa* libxcb* zlib* xz gcc gcc-c++ mingw32-gcc mingw32-gcc-c++ libXinerama* libxkbcommon* xcb* nss-devel glx-utils libevdev libgudev libinput mtdev dbus* libXcomposite-devel libXcursor-devel libXi-devel libXtst-devel libXdamage-devel libXrandr-devel ruby meson openssl-devel -y && \
	yum install perl libfontenc-devel -y && \
	yum group install "Development Tools" -y && \
	yum install llvm-toolset redhat-rpm-config clang clang-libs clang-devel llvm-devel libxshmfence libxshmfence-devel libatomic libstdc++ libstdc++-static ninja-build -y && \
	yum install gdb valgrind systemtap ltrace strace -y && \
	yum install gperf libX11 -y && \
	yum install postgresql-devel libpq -y && \
	yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y && \
	yum install p7zip lzip perl-IPC-Cmd -y && \
	yum install python3-html5lib bison flex nodejs cups-libs cups-devel libxkbfile libxkbfile-devel expat expat-devel -y

# Build Qt Source (native builds)
RUN \
	cd /opt/ && \
	wget -q https://download.qt.io/official_releases/qt/6.4/6.4.2/single/qt-everywhere-src-6.4.2.tar.xz && \
	tar -xf qt-everywhere-src-6.4.2.tar.xz && \
	rm qt-everywhere-src-6.4.2.tar.xz && \
	cd /opt/qt-everywhere-src-6.4.2 && \
	./configure -opensource -confirm-license -release -webengine-proprietary-codecs -nomake tests -nomake examples -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -xcb -sql-psql -sql-sqlite && \
	# sed -i -e 's|use_jumbo_build=true|use_jumbo_build=false|' ./qtwebengine/src/buildtools/config/common.pri && \
	cmake --build . --parallel
	
RUN \
	cmake --install .
		
ENV PATH="${PATH}:/usr/local/Qt-6.4.2/bin"
ENTRYPOINT ["/bin/bash"]