# Compile Environment for Qt Applications (windows)
# Use for apps that require QtWebEngine, otherwise recommend using the linux container with MXE
# DF Supply, Inc.
# Scott Moore
# 2/26/2022

FROM mcr.microsoft.com/windows/servercore:ltsc2022

SHELL ["cmd", "/S", "/C"]

# Install chocolatey
RUN powershell -NoProfile -ExecutionPolicy Bypass -Command \
    $Env:chocolateyVersion = '0.10.15' ; \
    $Env:chocolateyUseWindowsCompression = 'false' ; \
    "[Net.ServicePointManager]::SecurityProtocol = \"tls12, tls11, tls\"; iex ((New-Object System.Net.WebClient).DownloadString('http://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin" && \
    choco feature enable -n=allowGlobalConfirmation
    
# Install Curl
RUN choco install curl

# Install .net 4.8
RUN choco install dotnetfx

# Install MSVC 2019
RUN choco install visualstudio2019buildtools && \
	choco install visualstudio2019-workload-vctools && \
	choco install visualstudio2019-workload-universal && \
	choco install visualstudio2019-workload-nativedesktop && \
	choco install visualstudio2019-workload-universalbuildtools

# Install Git
RUN	choco install git
		
# Install JOM for multi-core builds
RUN choco install jom

# Install Perl
RUN choco install strawberryperl

RUN ["C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\Common7\\Tools\\VsDevCmd.bat"]

RUN cd c:\

# Setup build directories
RUN \
	mkdir build-env && \
	cd build-env

# Download Qt Source
RUN \
	git clone https://github.com/qt/qt5 && \
	cd qt5 && \
	git checkout 5.15.2 && \
	git submodule update --init --recursive
	
# Build Qt Source
RUN \
	configure -opensource -confirm-license -release -webengine-proprietary-codecs -nomake tests -nomake examples -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -sql-psql -sql-sqlite -platform=win32-msvc && \
	jom
	
ENTRYPOINT ["C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\Common7\\Tools\\VsDevCmd.bat", "&&", "powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]