# Compile Environment for Qt Applications (windows)
# Use for apps that require QtWebEngine, you use can also use the linux container with MXE (if not required)
# DF Supply, Inc.
# Scott Moore
# 2/26/2022

FROM mcr.microsoft.com/windows/servercore:ltsc2022 as imagebase

# Install chocolatey
RUN powershell -NoProfile -ExecutionPolicy Bypass -Command \
	$Env:chocolateyVersion = '0.10.15' ; \
	$Env:chocolateyUseWindowsCompression = 'false' ; \
	"[Net.ServicePointManager]::SecurityProtocol = \"tls12, tls11, tls\"; iex ((New-Object System.Net.WebClient).DownloadString('http://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin" && \
	choco feature enable -n=allowGlobalConfirmation
    
# Install Curl
RUN choco install curl --version=7.81.0

# Install .net 4.8
RUN choco install dotnetfx

# Install MSVC 2022
RUN \
	choco install visualstudio2022buildtools --ignore-package-exit-codes=3010 && \
	choco install visualstudio2022-workload-vctools --ignore-package-exit-codes=3010 --execution-timeout=7200 --package-parameters "--allWorkloads --includeRecommended --includeOptional "

# Reboot required after VS2022-workload-vctools
FROM imagebase
RUN \
	choco install visualstudio2022-workload-universal --ignore-package-exit-codes=3010 --execution-timeout=7200 --package-parameters "--allWorkloads --includeRecommended --includeOptional " && \
	choco install visualstudio2022-workload-nativedesktop --ignore-package-exit-codes=3010 --execution-timeout=7200 --package-parameters "--allWorkloads --includeRecommended --includeOptional " && \
	choco install visualstudio2022-workload-universalbuildtools --ignore-package-exit-codes=3010 --execution-timeout=7200 --package-parameters "--allWorkloads --includeRecommended --includeOptional "

# Install Git
RUN	choco install git
		
# Install JOM for multi-core builds
RUN choco install jom

# Install Perl
RUN choco install strawberryperl

# Install Ruby
RUN choco install ruby

# Install Python
RUN choco install python2

# Install sed
RUN choco install sed

# Setup build directories
RUN \
	mkdir build-env && \
	mkdir b

# vcpkg and required packages
RUN \
	git clone https://github.com/microsoft/vcpkg && \
	cd vcpkg && \
	bootstrap-vcpkg.bat && \
	vcpkg install protobuf:x64-windows && \
	vcpkg install qtbase[sql-psql]:x64-windows && \
	vcpkg install qtwebengine:x64-windows --x-buildtrees-root=C:\b\ && \
	vcpkg install qt:x64-windows && \
	vcpkg install qt5compat:x64-windows && \
	vcpkg install qtshadertools:x64-windows && \
	vcpkg install qtactiveqt:x64-windows && \
	vcpkg install qtapplicationmanager:x64-windows && \
	vcpkg install qtcharts:x64-windows && \
	vcpkg install qtcoap:x64-windows && \
	vcpkg install qtconnectivity:x64-windows && \
	vcpkg install qtdatavis3d:x64-windows && \
	vcpkg install qtdeclarative:x64-windows && \
	vcpkg install qtdeviceutilities:x64-windows && \
	vcpkg install qtimageformats:x64-windows && \
	vcpkg install qtinterfaceframework:x64-windows && \
	vcpkg install qtlocation:x64-windows && \
	vcpkg install qtmultimedia:x64-windows && \
	vcpkg install qtnetworkauth:x64-windows && \
	vcpkg install qtopcua:x64-windows && \
	vcpkg install qtpositioning:x64-windows && \
	vcpkg install qtquick3d:x64-windows && \
	vcpkg install qtquickcontrols2:x64-windows && \
	vcpkg install qtsvg:x64-windows && \
	vcpkg install qttools:x64-windows && \
	vcpkg install qttranslations:x64-windows && \
	vcpkg install qtwebchannel:x64-windows && \
	vcpkg install qtwebsockets:x64-windows && \
	vcpkg install qtwebview:x64-windows && \
	vcpkg install openssl:x64-windows && \
	vcpkg install zlib:x64-windows && \
	vcpkg install libpq:x64-windows && \
	vcpkg integrate install

# Bootstrapping msvc tools
SHELL ["powershell"]
RUN Install-PackageProvider NuGet -Force
RUN Install-Module -Name WintellectPowerShell -Force
RUN rm C:\vcpkg\installed\x64-windows\tools\qt5\bin\qt.conf

	
ENTRYPOINT ["C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat", "&&", "powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]]
