# Compile Environment for Qt Applications (linux)
# DF Supply, Inc.
# Scott Moore
# 2/24/2022

FROM registry.access.redhat.com/ubi8/ubi

RUN \
	yum update -y && \
	yum install yum-utils -y && \
	yum-config-manager --enable codeready-builder-for-rhel-8-x86_64-rpms && \
	yum install wget make cmake *mesa* libxcb* zlib* xz gcc gcc-c++ mingw32-gcc mingw32-gcc-c++ libXinerama* libxkbcommon* xcb* nss-devel glx-utils libevdev libgudev libinput mtdev python2 dbus* libXcomposite-devel libXcursor-devel libXi-devel libXtst-devel libXdamage-devel libXrandr-devel ruby meson openssl-devel -y && \
	alternatives --set python /usr/bin/python2 && \
	yum group install "Development Tools" -y && \
	yum module enable llvm-toolset:rhel8 -y && \
	yum install llvm-toolset redhat-rpm-config clang llvm-devel libatomic libstdc++ libstdc++-static ninja-build -y && \
	yum install gdb valgrind systemtap ltrace strace -y && \
	yum install gperf libX11 -y && \
	yum module reset postgresql -y && \
	yum module enable postgresql:13 -y && \
	yum install postgresql-devel postgresql-server-devel libpq -y && \
	yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y && \
	yum install p7zip lzip perl-IPC-Cmd -y

# Build Qt Source (native builds)
RUN \
	cd /opt/ && \
	wget -q http://download.qt.io/official_releases/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz && \
	tar -xf qt-everywhere-src-5.15.2.tar.xz && \
	rm qt-everywhere-src-5.15.2.tar.xz && \
	cd /opt/qt-everywhere-src-5.15.2 && \
	./configure -opensource -confirm-license -release -webengine-proprietary-codecs -nomake tests -nomake examples -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -xcb -sql-psql -sql-sqlite && \
	sed -i -e 's|use_jumbo_build=true|use_jumbo_build=false|' ./qtwebengine/src/buildtools/config/common.pri && \
	make -j$(nproc) NINJAJOBS=-j30 && \
	make install
	
# Build gdk-pixbuf (needed for MXE + not available in any RedHat package)
RUN \
	cd /opt/ && \
	wget -q https://download.gnome.org/sources/gdk-pixbuf/2.42/gdk-pixbuf-2.42.6.tar.xz && \
	tar -xf gdk-pixbuf-2.42.6.tar.xz && \
	rm gdk-pixbuf-2.42.6.tar.xz && \
	cd /opt/gdk-pixbuf-2.42.6 && \
	meson --prefix=/usr --buildtype=release --wrap-mode=nofallback ./build && \
	cd build && \
	ninja && \
	ninja install
	
# Build Qt in MXE (cross-platform)
RUN \
	yum install autoconf automake bash bison bzip2 flex gcc-c++ gdk-pixbuf2-devel gettext git gperf intltool libtool lzip make mesa-libGL-devel openssl openssl-devel p7zip patch perl python39 python3-mako ruby sed unzip wget which xz -y && \
	cd /opt/ && \
	git clone https://github.com/mxe/mxe.git && \
	cd mxe && \
	make MXE_TARGETS=x86_64-w64-mingw32.static qt5 -j$(nproc)

	
ENV PATH="${PATH}:/usr/local/Qt-5.15.2/bin"
ENTRYPOINT ["/bin/bash"]